name: Test pre-commit, code and docs

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
  - cron: '22 12 * * *'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
  test_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          make dev
          pip freeze > requirements.txt
      - uses: actions/upload-artifact@v4
        with:
          name: requirements
          path: requirements.txt
      - name: Test documentation
        env:
          TIDY3D_USER: ${{ secrets.TIDY3D_EMAIL }}
          TIDY3D_PASS: ${{ secrets.TIDY3D_PASSWORD }}
          DISPLAY: 1.0
          DOCS: True
          GDSFACTORY_DISPLAY_TYPE: klayout
        run: |
          mkdir -p $HOME/.tidy3d
          make docs
          python .github/test_doc_errors.py
